language: r
warnings_are_errors: true

r_github_packages:
  - jimhester/lintr

script:
  - R CMD INSTALL $PKG_TARBALL
  - LINTR_COMMENT_BOT=false
  - Rscript -e 'lintr::lint_package(linters = lintr::with_defaults(line_length_linter = lintr::line_length_linter(120)))'
