language: r
warnings_are_errors: true

r_github_packages:
  - jimhester/lintr

script:
  - LINTR_COMMENT_BOT=false
  - Rscript -e 'lint_err <- lintr::lint_package(linters = lintr::with_defaults(line_length_linter = lintr::line_length_linter(120))); if (length(lint_err) > 0) {print(lint_err); stop()}'
